project_id = "neriayolipcupycirwhf"

[functions.generate-questions]
verify_jwt = true

[functions.generate-plan]
verify_jwt = true

[functions.generate-kanban-tasks]
verify_jwt = true

[functions.generate-strategy]
verify_jwt = false
